export const genres = {
    Fiction: {
        Fantasy: [
            "Magical worlds",
            "Epic quests",
            "Mythical creatures",
            "Good vs. Evil",
            "Ancient prophecies",
        ],
        "Science Fiction": [
            "Future technology",
            "Space exploration",
            "Time travel",
            "Alien civilizations",
            "Dystopian futures",
        ],
        Mystery: [
            "Whodunit",
            "Private detectives",
            "Unsolved cases",
            "Hidden secrets",
            "Red herrings",
        ],
        Thriller: [
            "High stakes",
            "Puzzles and clues",
            "Chases and escapes",
            "Psychological tension",
            "Twists and turns",
        ],
        Horror: [
            "Supernatural entities",
            "Psychological fear",
            "Gothic settings",
            "Survival horror",
            "Creepy atmospheres",
        ],
        Romance: [
            "Forbidden love",
            "Unrequited love",
            "Happily ever after",
            "Love triangles",
            "Second chances",
        ],
        "Historical Fiction": [
            "Period settings",
            "Historical events",
            "Cultural practices",
            "Famous figures",
            "Social issues",
        ],
        "Literary Fiction": [
            "Character studies",
            "Existential themes",
            "Social commentary",
            "Complex narratives",
            "Emotional depth",
        ],
        Adventure: [
            "Heroic journeys",
            "Discovery",
            "Danger and excitement",
            "Exploration",
            "Overcoming obstacles",
        ],
        Dystopian: [
            "Oppressive regimes",
            "Survival struggles",
            "Social collapse",
            "Resistance movements",
            "Loss of freedom",
        ],
        "Magical Realism": [
            "Blending reality and fantasy",
            "Everyday magic",
            "Cultural myths",
            "Unexplained phenomena",
            "Symbolism",
        ],
    },
    "Non-Fiction": {
        "Biography/Autobiography": [
            "Personal achievements",
            "Life stories",
            "Historical impact",
            "Overcoming adversity",
            "Influential figures",
        ],
        Memoir: [
            "Personal experiences",
            "Reflective narratives",
            "Self-discovery",
            "Emotional journeys",
            "Key life events",
        ],
        "Self-Help": [
            "Personal growth",
            "Mental health",
            "Productivity tips",
            "Motivation",
            "Relationship advice",
        ],
        "True Crime": [
            "Criminal investigations",
            "Real-life mysteries",
            "Forensic details",
            "Notorious criminals",
            "Legal proceedings",
        ],
        Essays: [
            "Social commentary",
            "Personal reflections",
            "Cultural observations",
            "Philosophical musings",
            "Critical analysis",
        ],
        Journalism: [
            "Investigative reporting",
            "Current events",
            "Human interest stories",
            "Political coverage",
            "In-depth analysis",
        ],
        Philosophy: [
            "Existential questions",
            "Ethical dilemmas",
            "Metaphysical concepts",
            "The nature of reality",
            "Logic and reasoning",
        ],
        "Religion/Spirituality": [
            "Faith and belief systems",
            "Religious practices",
            "Spiritual growth",
            "Sacred texts",
            "Moral teachings",
        ],
        Science: [
            "Scientific discoveries",
            "Research and experiments",
            "Natural phenomena",
            "Technological advancements",
            "Theories and principles",
        ],
        "Travel Writing": [
            "Cultural experiences",
            "Travel adventures",
            "Geographic exploration",
            "Local traditions",
            "Personal reflections",
        ],
    },
    Poetry: {
        "Lyric Poetry": [
            "Emotional expression",
            "Personal feelings",
            "Imagery",
            "Musical quality",
            "Brief and intense",
        ],
        "Narrative Poetry": [
            "Storytelling",
            "Character development",
            "Plot and structure",
            "Setting and atmosphere",
            "Narrative voice",
        ],
        "Epic Poetry": [
            "Heroic deeds",
            "Grand scale",
            "Mythical elements",
            "Cultural legends",
            "Historical themes",
        ],
        "Dramatic Poetry": [
            "Conflict and dialogue",
            "Stage performance",
            "Character interaction",
            "Emotional intensity",
            "Theatrical elements",
        ],
        Haiku: [
            "Nature imagery",
            "Seasonal themes",
            "Simplicity",
            "Momentary reflections",
            "17 syllables",
        ],
    },
    Drama: {
        Comedy: [
            "Humor and wit",
            "Happy endings",
            "Romantic entanglements",
            "Social satire",
            "Light-hearted themes",
        ],
        Tragedy: [
            "Downfall of protagonists",
            "Fatal flaws",
            "Emotional suffering",
            "Moral lessons",
            "Catastrophic events",
        ],
        Tragicomedy: [
            "Mix of humor and tragedy",
            "Complex characters",
            "Ironic situations",
            "Emotional depth",
            "Mixed tone",
        ],
        Farce: [
            "Exaggerated situations",
            "Physical comedy",
            "Mistaken identities",
            "Slapstick humor",
            "Ridiculous scenarios",
        ],
        Melodrama: [
            "Exaggerated emotions",
            "Clear moral distinctions",
            "Sensational plots",
            "Stock characters",
            "Dramatic conflicts",
        ],
    },
    "Children's Literature": {
        "Picture Books": [
            "Illustrated stories",
            "Simple narratives",
            "Early literacy",
            "Engaging visuals",
            "Moral lessons",
        ],
        "Young Adult (YA)": [
            "Coming-of-age",
            "Personal identity",
            "Romantic relationships",
            "Social issues",
            "Adventure and exploration",
        ],
        "Middle Grade": [
            "Friendship and family",
            "Adventures and quests",
            "School life",
            "Moral lessons",
            "Imaginative scenarios",
        ],
        Fables: [
            "Moral lessons",
            "Animal characters",
            "Simple narratives",
            "Clear morals",
            "Traditional storytelling",
        ],
        "Fairy Tales": [
            "Magical elements",
            "Good vs. Evil",
            "Royalty and magic",
            "Moral lessons",
            "Enchanting settings",
        ],
    },

};

export const mainCharacters= {
    King: [
        "Humor and wit",
        "Happy endings",
        "Romantic entanglements",
        "Social satire",
        "Light-hearted themes",
    ],
    Queen: [
        "Downfall of protagonists",
        "Fatal flaws",
        "Emotional suffering",
        "Moral lessons",
        "Catastrophic events",
    ],
    Carpenter: [
        "Mix of humor and tragedy",
        "Complex characters",
        "Ironic situations",
        "Emotional depth",
        "Mixed tone",
    ],
    Nurse: [
        "Exaggerated situations",
        "Physical comedy",
        "Mistaken identities",
        "Slapstick humor",
        "Ridiculous scenarios",
    ],
    Teacher: [
        "Exaggerated emotions",
        "Clear moral distinctions",
        "Sensational plots",
        "Stock characters",
        "Dramatic conflicts",
    ],
}


export const steps = [
    "Basic Information",
    "Reading Preference",
    "Character Preference",
    "Story Setting",
    "Accesibility and Format Preference",
    "Additional Preferences",
];

export const unsuitableSubGenresForKids = ["Horror", "Fantasy", "Mystery"];
